language: java
jdk: openjdk11

jobs:
    include:
        - stage: build
          if: branch IN (master, releases)
          install: skip
          script: ./gradlew clean build

        - stage: test
          if: branch IN (master, releases)
          install: skip
          script: ./gradlew unitTests

        - stage: publish-snapshot
          if: branch = master
          install: skip
          script: ./gradlew artifactoryPublish

        - stage: publish-release
          if: branch = releases
          install: skip
          script: ./gradlew bintrayUpload

env:
    global:
        # BINTRAY_USER
        - secure: Awo+2nC6m5iknCnvoXyb1/SlC7HI1hOeeGWwzaenuwkiu+SveqB7HQeM+ANUtbOIGwASSxSszRgMV/fzSkgwP8HycMgVDEBwDSv8CHxVkYyDBgdPJ4frWph1D9hNzvZp/LjNQ1SE28Ugzw7wA87TvuqHzGt+cRcD06oAJQuBcMkMkhF917IgrJKr+UWaf62gv7tpOa8buUgcZl78FmyuQIMHR6bCP7Sq7R7271/ny3Nb1RSm6DYbYlBG41ZDbSdEAOZHz87cEi+2nPJdNwQ040RTGo8E3nBsM3spXwBWVeGGyfIccAQZgubY5g5axAgnGe6x0ep9gs0i3KxX66be4ulZKH4quD4CtrSHZqLu8OooQgfat5yT+4ypXhIe1fzH3zsYf8DalW5SSzB6y+TcTN77w5lch4D351l3RtK7TsC3FH9DcPSfquui48RDjKsCVscqE29MuflVwZaBllEBqtSOE02HZk3xlsknsfJlemMpElrkOPmZU6awzRJhyfQYEC/6elOM+NVAjNiHL3FjGHg1ZHHrmoVqczwSeDFP5V58jF2mG40jF3apfK3z2hXT7KuY/JeM6E0MVp0SJqIXii/Y1ResWmW1MohSpg789duH/9zxV/QVHnyp+pqUWOaUurVmZVTBajM0Z7hHEeXOo9OiKBLzsGA13iX8dtpwCqs=
        # BINTRAY_API_KEY
        - secure: aInnZf5Ow53SyY9ZWIL9FvKX49piMLG4c7zNytzTuWIKNH8UrznD5rVUMkz6OmcM+vXtK+i2eLGuQOV3IoUFDnnBsnsbgcjdF1fLyrk3r11dS0DNvPqHmThz9rtGHpBWvaiGIJfZs+Gzz9kR0ac/kl7CUcG2mH+SgAj89wy2hxe6nIsmjB7pi438lrwx9IzM4F0uOzEPsKlJ128rZmHFK8Pnp7URSps47vhB5uC8vT8LHs82XKQXWdSOINYqM8bvh2zyRrRwqNuT7scf3jgd7xdqZNktv1/YBHLyE6omlYdokF7mTHjmN4VO/H4S7X1BooRZkMGAaTCG7HVTJU8/tGfv0uvpJ5GP3rD3E+S9jy1yX82BJojhnucr/nzsrPa7c3o3o1+XQm4CWAcz/fFA+ixWGE+dK9aZXqJIQB/hS4m78+rIQeM7qfF0sPuXQbxGc7Vqvskv6tgCpCnniNRTP0XCRjxBAB7B86snmOFrClMw2IaaPTVNWKb4tRWPXi2MyFiRbFXmWt7JsyeXCrI+esQPfOwhsXimX7ntz/Yry0h/BARo78Nh8X4qpCGCV7mrbYqA8ArBv2LiPWJTfTn50V5y11GdrI4lXKQPYAqIyGW2Dh+JAtY4XcIz4KrjpPhcUme4+CNq2Grt5cUa49UTJ84fpkqdFHOPcAwqIRu1IK0=
