version: '2.1'
services:
    elasticsearch:
        build: .
        ports:
            - 9200:9200
            - 9300:9300
            - 11000:8000
        volumes:
            - es-data:/usr/share/elasticsearch/data/
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        ports:
            - 5601:5601

volumes:
    es-data:
        name: es-data
